export type RootStackParamList = {
  OnboardingScreen: undefined;
  LocationPermissionScreen: { returnTo?: { screen: keyof RootStackParamList; params?: any } } | undefined;
  AuthScreen: { returnTo?: { screen: keyof RootStackParamList; params?: any } } | undefined;
  SignUpScreen: { newUser?: any; returnTo?: { screen: keyof RootStackParamList; params?: any } } | undefined;
  SignInScreen: undefined;
  SplashScreen: undefined;
  ErrorScreen: undefined;
  RideCreatedScreen: undefined;
  RideRequestedScreen: undefined;
  BookingScreen: undefined;
  HomeScreen: undefined;
  ProfileScreen: undefined;
  BookingsScreen: undefined;
  PersonalInformationScreen: undefined;
  PassengersHistoryScreen: undefined;
  CreateRide: undefined;
  AvailableRidesScreen: { 
    fromLocation: string; 
    toLocation: string;
    fromCoordinates?: { latitude: number; longitude: number };
    toCoordinates?: { latitude: number; longitude: number };
  };
  AvailableRidesSelectedScreen: undefined;
  DefaultAddressScreen: undefined;
  NotificationsScreen: undefined;
  AccountSettingsScreen: undefined;
  PassengerInfoScreen: undefined;
  ChatMessages: {
    chatId: string;
    chatTitle: string;
    chatSubtitle: string;
    isGroupChat: boolean;
  };
  TripsListScreen: undefined;
  RideDetailsScreen: { ride: any };
  NearbyRidesScreen: undefined;
  PrivacyPolicyScreen: undefined;
  TermsOfServiceScreen: undefined;
};
