import { StyleSheet } from 'react-native';
import AppColors from '../../design_systems/colors';

export const chatScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.primaryLightGreen,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  instituteName: {
    fontSize: 12,
    color: AppColors.basicBlack,
    marginLeft: 4,
    fontFamily: 'NunitoSans-Regular',
  },
  instituteNumber: {
    fontSize: 10,
    color: AppColors.basicBlack,
    marginLeft: 4,
    marginTop: 1,
    fontFamily: 'NunitoSans-Regular',
  },
  appName: {
    fontSize: 18,
    fontWeight: 'normal',
    color: AppColors.basicBlack,
    fontFamily: 'Trap-Bold',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: 48,
  },
  chatTitle: {
    fontSize: 20,
    color: AppColors.basicBlack,
    marginLeft: 8,
    fontFamily: 'NunitoSans-Regular',
  },
  chatSubtitleNumber: {
    fontSize: 14,
    color: AppColors.basicBlack,
    marginLeft: 8,
    marginTop: 2,
    fontFamily: 'NunitoSans-Regular',
  },
  chatSubtitle: {
    fontSize: 12,
    color: AppColors.basicBlack,
    opacity: 0.7,
    marginLeft: 8,
    marginTop: 2,
    fontFamily: 'NunitoSans-Regular',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingVertical: 12,
    justifyContent: 'space-around',
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 25,
  },
  navItem: {
    padding: 8,
  },
});

export const passengerInfoStyles = StyleSheet.create({
  ...chatScreenStyles,
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
    paddingHorizontal: 0,
    gap: 12,
  },
  toggleButtonActive: {
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: AppColors.secondaryDarkGreen,
  },
  toggleButtonInactive: {
    backgroundColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: AppColors.secondaryDarkGreen,
  },
  toggleTextActive: {
    color: AppColors.primaryLightGreen,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Regular',
  },
  toggleTextInactive: {
    color: AppColors.secondaryDarkGreen,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Regular',
  },
  destinationsList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  destinationItem: {
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginBottom: 12,
  },
  destinationText: {
    color: AppColors.basicWhite,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Regular',
  },
});

export const tripInfoStyles = StyleSheet.create({
  ...chatScreenStyles,
  chatHeader: {
    ...chatScreenStyles.chatHeader,
    marginTop: 48,
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
    paddingHorizontal: 0,
    gap: 12,
  },
  toggleButtonActive: {
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: AppColors.secondaryDarkGreen,
  },
  toggleButtonInactive: {
    backgroundColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: AppColors.secondaryDarkGreen,
  },
  toggleTextActive: {
    color: AppColors.primaryLightGreen,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Regular',
  },
  toggleTextInactive: {
    color: AppColors.secondaryDarkGreen,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Regular',
  },
  tripsList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  tripItem: {
    backgroundColor: AppColors.secondaryDarkGreen,
    borderRadius: 20,
    marginBottom: 12,
    padding: 16,
    marginTop: 5  ,
  },
  tripContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tripInfo: {
    flex: 1,
  },
  tripDestination: {
    color: AppColors.basicWhite,
    fontSize: 18,
    marginBottom: 4,
    fontFamily: 'NunitoSans-Regular',
  },
  tripDate: {
    color: AppColors.primaryLightGreen,
    fontSize: 12,
    opacity: 0.7,
    fontFamily: 'NunitoSans-Regular',
  },
  tripDetails: {
    alignItems: 'flex-end',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 4,
  },
  tripPrice: {
    color: AppColors.basicWhite,
    fontSize: 12,
    marginLeft: 4,
    fontFamily: 'NunitoSans-Regular',
  },
  tripParticipants: {
    color: AppColors.basicWhite,
    fontSize: 10,
    opacity: 0.7,
    fontFamily: 'NunitoSans-Regular',
  },
});

export const chatMessagesStyles = StyleSheet.create({
  ...chatScreenStyles,
  chatHeader: {
    ...chatScreenStyles.chatHeader,
    paddingVertical: 12,
  },
  chatInfo: {
    flex: 1,
    marginLeft: 12,
  },
  chatTitle: {
    fontSize: 22,
    color: AppColors.basicBlack,
    fontFamily: 'NunitoSans-Regular',
  },
  chatSubtitle: {
    fontSize: 12,
    color: AppColors.basicBlack,
    opacity: 0.7,
    marginTop: 2,
    fontFamily: 'NunitoSans-Regular',
  },
  carIcon: {
    backgroundColor: AppColors.basicWhite,
    padding: 8,
    borderRadius: 20,
  },
  infoMessage: {
    backgroundColor: AppColors.basicWhite,
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 12,
    borderRadius: 15,
    opacity: 0.9,
  },
  infoText: {
    fontSize: 12,
    color: AppColors.basicBlack,
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
  },
  messagesContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  messageReceived: {
    backgroundColor: AppColors.secondaryDarkGreen,
    padding: 12,
    borderRadius: 15,
    marginVertical: 4,
    maxWidth: '80%',
    alignSelf: 'flex-start',
  },
  messageSent: {
    backgroundColor: AppColors.basicWhite,
    padding: 12,
    borderRadius: 15,
    marginVertical: 4,
    maxWidth: '80%',
    alignSelf: 'flex-end',
  },
  messageText: {
    color: AppColors.basicWhite,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'NunitoSans-Regular',
  },
  messageTextSent: {
    color: AppColors.basicBlack,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'NunitoSans-Regular',
  },
  messageTime: {
    color: AppColors.basicWhite,
    fontSize: 10,
    marginTop: 4,
    alignSelf: 'flex-end',
    opacity: 0.7,
    fontFamily: 'NunitoSans-Regular',
  },
  messageTimeSent: {
    color: AppColors.basicBlack,
    fontSize: 10,
    marginTop: 4,
    alignSelf: 'flex-end',
    opacity: 0.7,
    fontFamily: 'NunitoSans-Regular',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  textInput: {
    flex: 1,
    backgroundColor: AppColors.basicWhite,
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: AppColors.basicBlack,
    maxHeight: 100,
  },
  sendButton: {
    marginLeft: 8,
    padding: 12,
  },
  typingBarContainer: {
    paddingHorizontal: 26,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 44,
    borderWidth: 2.28,
    borderColor: AppColors.secondaryDarkGreen,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  typingBarText: {
    color: AppColors.basicBlack,
    fontSize: 16,
    flex: 1,
    fontFamily: 'NunitoSans-Regular',
  },
  typingBarIconContainer: {
    width: 35,
    height: 35,
    backgroundColor: 'transparent',
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 11,
  },
});

export default {
  chatScreenStyles,
  passengerInfoStyles,
  tripInfoStyles,
  chatMessagesStyles,
};