const fs    = require('fs');
const path  = require('path');
const axios = require('axios');

const POPULAR_LOCATIONS = {
  ahmedabad: [
    "Ahmedabad Junction",
    "Sardar Vallabhbhai Patel Airport",
    "CG Road",
    "SG Highway",
    "Maninagar",
    "Navrangpura",
    "Ellis Bridge",
    "Bodakdev",
    "Satellite",
    "Prahlad Nagar",
    "Bapunagar",
    "Naroda",
    "Paldi",
    "Vastrapur",
    "Drive-In Road",
    "Law Garden",
    "Sabarmati Ashram",
    "Gandhi Nagar",
    "Vatva",
    "Thaltej"
  ],
  aligarh: [
    "Aligarh Junction",
    "Aligarh Muslim University",
    "Medical Road (J.N. Medical College)",
    "Marris Road",
    "Centre Point",
    "Railway Road",
    "Jamia Urdu",
    "Dodpur",
    "Gandhi Park",
    "Upper Kot",
    "Masoodabad",
    "Tala Nagari",
    "Quarsi",
    "Khair Road",
    "Medical College"
  ],
  allahabad: [
    "Allahabad Junction",
    "Prayagraj Junction",
    "Civil Lines",
    "Katra",
    "Chowk",
    "Triveni Sangam",
    "Allahabad University",
    "High Court",
    "Naini",
    "Jhunsi",
    "Phaphamau",
    "Khuldabad",
    "Daraganj",
    "Colonelganj",
    "Govindpur"
  ],
  bangalore: [
    "Kempegowda International Airport",
    "Bangalore City Railway Station (Majestic)",
    "Majestic Bus Stand",
    "M.G. Road",
    "Brigade Road",
    "Koramangala",
    "Indiranagar",
    "Jayanagar",
    "Malleshwaram",
    "Whitefield",
    "Electronic City",
    "HSR Layout",
    "Basavanagudi",
    "Sadashivanagar",
    "Ulsoor",
    "Richmond Town",
    "Banashankari",
    "Yelahanka",
    "Marathahalli",
    "BTM Layout"
  ],
  bhopal: [
    "Bhopal Junction",
    "Rani Kamlapati Railway Station (Habibganj)",
    "Raja Bhoj Airport",
    "New Market",
    "MP Nagar",
    "Arera Colony",
    "BHEL Township",
    "Indrapuri",
    "TT Nagar",
    "Kolar Road",
    "Chowk Bazaar (Old Bhopal)",
    "Shyamla Hills",
    "Vallabh Bhavan",
    "MANIT (NIT Bhopal)",
    "Barkatullah University",
    "Misrod",
    "Govindpura",
    "Jawahar Chowk",
    "Berasia Road",
    "Karond"
  ],
  bhubaneswar: [
    "Bhubaneswar Railway Station",
    "Biju Patnaik International Airport",
    "Master Canteen Chowk",
    "Janpath",
    "Saheed Nagar",
    "Jayadev Vihar",
    "Chandrasekharpur",
    "Infocity",
    "KIIT University",
    "Old Town",
    "Lingaraj Temple Area",
    "Khandagiri",
    "Nayapalli",
    "Unit 1 Market",
    "Baramunda",
    "Patia",
    "Forest Park",
    "Esplanade (Ram Mandir area)",
    "Bapuji Nagar",
    "Bomikhal"
  ],
  chandigarh: [
    "Chandigarh Railway Station",
    "Chandigarh Airport",
    "Sector 17 (City Centre)",
    "Sector 22",
    "Sector 43 Bus Stand",
    "Sector 35",
    "Sector 7 (Madhya Marg)",
    "Sector 8",
    "Panjab University",
    "PGI Chandigarh",
    "Rock Garden",
    "Sukhna Lake",
    "Mohali",
    "Panchkula",
    "Industrial Area Phase I",
    "Manimajra",
    "Sector 26 (Grain Market)",
    "IT Park",
    "Daria",
    "Hallomajra"
  ],
  chennai: [
    "Chennai Central Railway Station",
    "Chennai International Airport",
    "Anna Salai (Mount Road)",
    "T. Nagar",
    "Koyambedu",
    "Velachery",
    "Adyar",
    "Mylapore",
    "Egmore",
    "Tambaram",
    "Porur",
    "Guindy",
    "Nungambakkam",
    "Thyagaraya Nagar (Pondy Bazaar)",
    "Thiruvanmiyur",
    "Perambur",
    "George Town (Parry's Corner)",
    "Old Mahabalipuram Road (OMR)",
    "Sholinganallur",
    "Sriperumbudur"
  ],
  coimbatore: [
    "Coimbatore International Airport",
    "Coimbatore Junction",
    "Gandhipuram",
    "RS Puram",
    "Peelamedu",
    "Saibaba Colony",
    "Race Course",
    "Town Hall",
    "Ukkadam",
    "Singanallur",
    "Vadavalli",
    "KK Pudur",
    "Avinashi Road",
    "Brookefields Mall",
    "Fun Republic Mall",
    "Podanur",
    "Kalapatti",
    "Thudiyalur",
    "Perur",
    "Saravanampatti"
  ],
  delhi: [
    "New Delhi Railway Station",
    "Old Delhi Railway Station",
    "Indira Gandhi International Airport",
    "Connaught Place",
    "Chandni Chowk",
    "Karol Bagh",
    "Paharganj",
    "Hauz Khas",
    "Saket",
    "Lajpat Nagar",
    "Dwarka",
    "Rohini",
    "Noida",
    "Gurgaon",
    "Nehru Place",
    "Janakpuri",
    "Vasant Kunj",
    "South Extension",
    "AIIMS (All India Institute of Medical Sciences)",
    "Delhi University (North Campus)"
  ],
  dhanbad: [
    "Dhanbad Junction",
    "Katras",
    "Jharia",
    "Saraidhela",
    "Govindpur",
    "Hirapur",
    "Bank More",
    "Sindri",
    "City Centre (Bank More)",
    "Barwadda",
    "Putki",
    "BCCL Township",
    "ISM (IIT Dhanbad)",
    "Dhansar",
    "Matkuria",
    "Kusunda",
    "Polyetchnic Chowk",
    "Steel Gate",
    "Bartand",
    "Chirkunda"
  ],
  gurgaon: [
    "MG Road (Gurugram)",
    "IFFCO Chowk",
    "Cyber City",
    "Udyog Vihar",
    "Golf Course Road",
    "Sohna Road",
    "DLF Phase 1",
    "DLF Phase 3 (Cyber Hub)",
    "Manesar",
    "Sector 14",
    "Sushant Lok",
    "Palam Vihar",
    "Huda City Center",
    "Medanta (Sector 38)",
    "Ambience Mall",
    "Rajiv Chowk (Gurgaon)",
    "Sector 29",
    "Dwarka Expressway",
    "South City",
    "Badshahpur"
  ],
  guwahati: [
    "Guwahati Railway Station (Paltan Bazaar)",
    "Lokpriya Gopinath Bordoloi Airport",
    "Paltan Bazaar",
    "Pan Bazaar",
    "Fancy Bazaar",
    "Ganeshguri",
    "Khanapara",
    "Beltola",
    "Dispur (Capital Complex)",
    "Maligaon",
    "Uzan Bazaar",
    "Chandmari",
    "Zoo Road",
    "Six Mile",
    "Ulubari",
    "Jalukbari",
    "Azara",
    "Noonmati",
    "Narengi",
    "Basistha"
  ],
  hyderabad: [
    "Rajiv Gandhi International Airport",
    "Hyderabad Deccan (Nampally) Station",
    "Secunderabad Junction",
    "HITEC City",
    "Gachibowli",
    "Madhapur",
    "Jubilee Hills",
    "Banjara Hills",
    "Somajiguda",
    "Begumpet",
    "Kondapur",
    "Kukatpally",
    "Charminar",
    "Mehdipatnam",
    "Abids",
    "L.B. Nagar",
    "Dilsukhnagar",
    "Necklace Road",
    "Tank Bund",
    "Falaknuma"
  ],
  indore: [
    "Indore Junction",
    "Devi Ahilyabai Holkar Airport",
    "Rajwada",
    "Sarafa Bazaar",
    "MG Road (Indore)",
    "Vijay Nagar",
    "Palasia",
    "Bhanwarkuan",
    "Rau (IIT Indore campus area)",
    "A.B. Road",
    "Bhawarkua",
    "Sudama Nagar",
    "Navlakha",
    "LIG Colony",
    "Dwarkapuri",
    "Eastern Ring Road",
    "Indore White Church",
    "Khajrana",
    "Rajendra Nagar",
    "Mhow"
  ],
  jaipur: [
    "Jaipur Junction",
    "Jaipur International Airport",
    "MI Road (Mirza Ismail Road)",
    "Bapu Bazaar",
    "Johari Bazaar",
    "Hawa Mahal Road",
    "Sindhi Camp Bus Stand",
    "Vaishali Nagar",
    "Mansarovar",
    "Malviya Nagar",
    "C-Scheme",
    "Amer Fort",
    "JLN Marg",
    "Ajmeri Gate",
    "Tonk Road",
    "Bani Park",
    "Raja Park",
    "Shyam Nagar",
    "Jawahar Circle",
    "Gopalpura"
  ],
  kanpur: [
    "Kanpur Central Railway Station",
    "Kanpur Anwarganj Station",
    "Kanpur Airport (Chakeri)",
    "IIT Kanpur",
    "CSJM University",
    "Kanpur Cantonment",
    "Civil Lines",
    "Swaroop Nagar",
    "Tilak Nagar",
    "Naveen Market",
    "The Mall (Mall Road)",
    "Govind Nagar",
    "Kidwai Nagar",
    "Panki",
    "Fazalganj",
    "Kalpi Road",
    "Shastri Nagar",
    "Kakadeo",
    "Lakhanpur",
    "Kalyanpur"
  ],
  kharagpur: [
    "Kharagpur Junction",
    "IIT Kharagpur Campus",
    "Hijli",
    "Prembazar",
    "Inda",
    "Kalaikunda",
    "Railway Workshop Area",
    "Malanchowk",
    "NH-6 Junction",
    "Chaudhury Bazaar",
    "Gole Bazaar",
    "Nimpura",
    "Talbagicha",
    "Midnapore Road",
    "Tech Market (IIT Campus)",
    "Kharagpur Bus Stand"
  ],
  kolkata: [
    "Howrah Junction",
    "Sealdah Station",
    "Netaji Subhas Chandra Bose Airport",
    "Park Street",
    "Esplanade (Dharmatala)",
    "B.B.D. Bagh (Dalhousie Square)",
    "Salt Lake City (Bidhannagar)",
    "New Town (Rajarhat)",
    "Gariahat",
    "Tollygunge",
    "Jadavpur",
    "Behala",
    "College Street",
    "Dum Dum",
    "Shyambazar",
    "Kalighat",
    "Alipore",
    "Ballygunge",
    "Howrah Maidan",
    "EM Bypass"
  ],
  lucknow: [
    "Charbagh Railway Station",
    "Chaudhary Charan Singh Airport (Amausi)",
    "Hazratganj",
    "Gomti Nagar",
    "Alambagh",
    "Aminabad",
    "Indira Nagar",
    "Aliganj",
    "Chowk",
    "Janakipuram",
    "Kaiserbagh",
    "Cantt Road (Lucknow Cantonment)",
    "Thakurganj",
    "Rajajipuram",
    "Faizabad Road",
    "Telibagh",
    "VRindavan Yojna",
    "Trans Gomti (Lucknow)",
    "Chinhat",
    "Dubagga"
  ],
  madurai: [
    "Madurai Airport",
    "Madurai Junction",
    "Meenakshi Amman Temple",
    "Mattuthavani Bus Stand",
    "Periyar Bus Stand",
    "K. Pudur",
    "Goripalayam",
    "Thirupparankundram",
    "Avaniyapuram",
    "Palanganatham",
    "Arasaradi",
    "Anna Nagar (Madurai)",
    "KK Nagar (Madurai)",
    "Simmakkal",
    "Thirunagar",
    "Tallakulam",
    "Vilakkuthoon",
    "Melur",
    "Thirumangalam",
    "Othakadai"
  ],
  manipal: [
    "MIT Manipal (Manipal Institute of Technology)",
    "Kasturba Medical College (KMC)",
    "Manipal University (MAHE)",
    "Tiger Circle",
    "Manipal Bus Stand",
    "Manipal Lake",
    "End Point",
    "Vidyarathna Nagar",
    "Eshwar Nagar",
    "Madhav Nagar",
    "Ananth Nagar",
    "Perampalli",
    "Udupi Railway Station",
    "Malpe Beach",
    "Kunjibettu",
    "Santhekatte",
    "MIT Hostel Blocks",
    "Templar Town",
    "KC Road",
    "Manipal Main Road"
  ],
  mangalore: [
    "Mangalore Central Railway Station",
    "Mangalore Junction (Kankanady)",
    "Mangalore International Airport",
    "Hampankatta",
    "Kadri",
    "Lalbagh",
    "Bejai",
    "Kankanadi",
    "Balmatta",
    "Car Street",
    "Pandeshwar",
    "Surathkal",
    "Panambur",
    "Ullal",
    "Derebail",
    "Kulur",
    "Bunder (Old Port)",
    "Kudroli",
    "Infantry Road",
    "Kavoor"
  ],
  mumbai: [
    "Chhatrapati Shivaji Maharaj Terminus (CST)",
    "Mumbai Central Station",
    "Bandra",
    "Andheri",
    "Dadar",
    "Colaba",
    "Nariman Point",
    "Marine Drive",
    "Juhu",
    "Bandra Kurla Complex (BKC)",
    "Powai",
    "Churchgate",
    "Worli",
    "Lower Parel",
    "Goregaon",
    "Borivali",
    "Navi Mumbai",
    "Thane",
    "Mulund",
    "Chembur",
    "Ghatkopar",
    "Vashi"
  ],
  mysore: [
    "Mysore Junction",
    "Mysore Airport (Mandakalli)",
    "Mysore Palace",
    "Chamundi Hills",
    "Jayalakshmipuram",
    "Vijayanagar",
    "Gokulam",
    "Hebbal (Mysore)",
    "Saraswathipuram",
    "Lashkar Mohalla",
    "Nazarbad",
    "Kuvempunagar",
    "Krishnaraja Boulevard",
    "Nanjangud Road",
    "VV Mohalla",
    "Siddhartha Layout",
    "Banumaiah Circle",
    "Infosys Campus",
    "Yadavagiri",
    "Hinkal"
  ],
  nagpur: [
    "Nagpur Junction",
    "Dr. Babasaheb Ambedkar International Airport",
    "Sitabuldi",
    "Sadar",
    "Civil Lines",
    "Dharampeth",
    "Ramdaspeth",
    "Itwari",
    "MIHAN",
    "Butibori",
    "Wardha Road",
    "Kamptee Road",
    "Koradi",
    "Mahal",
    "Cotton Market",
    "Ajni",
    "Jaripatka",
    "Manish Nagar",
    "Reshim Bagh",
    "Shankar Nagar"
  ],
  "navi mumbai": [
    "Vashi",
    "Nerul",
    "Belapur",
    "Kharghar",
    "Panvel",
    "Airoli",
    "Kopar Khairane",
    "Ghansoli",
    "Sanpada",
    "Seawoods",
    "Ulwe",
    "CBD Belapur",
    "Turbhe",
    "Rabale",
    "Mahape",
    "Kalamboli",
    "Kamothe",
    "New Panvel",
    "Digha",
    "Juinagar"
  ],
  noida: [
    "Sector 62",
    "Sector 18 (Atta Market)",
    "Noida City Centre (Sector 32)",
    "Film City (Sector 16A)",
    "Greater Noida",
    "Yamuna Expressway",
    "Sector 15",
    "Sector 37",
    "Sector 21 (Noida Stadium)",
    "Amity University (Sector 125)",
    "Pari Chowk",
    "Sector 50",
    "Sector 135",
    "Noida-Greater Noida Expressway",
    "Sector 110",
    "Sector 75",
    "Botanical Garden",
    "GIP Mall (Sector 38A)",
    "Okhla Bird Sanctuary",
    "Sector 44"
  ],
  patna: [
    "Patna Junction",
    "Jay Prakash Narayan International Airport",
    "Gandhi Maidan",
    "Fraser Road",
    "Ashok Rajpath",
    "Kankarbagh",
    "Boring Road",
    "Bailey Road",
    "Danapur",
    "Patna Sahib (Harmandir Takht)",
    "Patna University",
    "NIT Patna (Ashok Rajpath)",
    "Rajendra Nagar",
    "Phulwari Sharif",
    "Saguna More",
    "AIIMS Patna",
    "Dak Bunglow Chowk",
    "Patliputra Colony",
    "Anisabad",
    "Agam Kuan"
  ],
  pilani: [
    "BITS Pilani Campus",
    "Pilani Bus Stand",
    "Vidya Vihar",
    "CEERI Pilani",
    "Pilani Chowk",
    "Birla Mandir, Pilani",
    "Museum (Birla Science Centre)",
    "Nawa Bazar",
    "Haridas Colony",
    "North Campus Gate",
    "Pilani Hospital",
    "Chirawa Road",
    "Baikner",
    "Dharmsinghwala",
    "Katariyo Ka Bass",
    "Nalwa Road",
    "Pilani Gaushala",
    "Pilani Mela Ground",
    "Kasbi Market",
    "Gyan Vihar"
  ],
  pondicherry: [
    "Pondicherry Railway Station",
    "French Quarter (White Town)",
    "Auroville",
    "Paradise Beach",
    "Promenade Beach",
    "Bharathi Park",
    "Goubert Market",
    "Botanical Garden",
    "Chunnambar Boat House",
    "Serenity Beach",
    "Aurobindo Ashram",
    "Manakula Vinayagar Temple",
    "Raj Niwas",
    "Pondy Bazaar",
    "Lawspet",
    "University of Pondicherry",
    "Mission Street",
    "Courbon Street",
    "Villiyanur",
    "Thavalakuppam"
  ],
  pune: [
    "Pune Junction",
    "Pune International Airport (Lohegaon)",
    "Hinjewadi",
    "Viman Nagar",
    "Koregaon Park",
    "Aundh",
    "Kalyani Nagar",
    "Shivaji Nagar",
    "Deccan Gymkhana",
    "FC Road (Fergusson College Road)",
    "Swargate",
    "Kothrud",
    "Magarpatta City",
    "Kharadi",
    "Hadapsar",
    "Baner",
    "Sinhagad Road",
    "Bhosari",
    "Camp (MG Road Pune)",
    "Bibwewadi"
  ],
  raipur: [
    "Raipur Junction",
    "Swami Vivekananda Airport",
    "Pandri Market",
    "Naya Raipur (Atal Nagar)",
    "Gudhiyari",
    "Tatibandh",
    "Telibandha (Marine Drive Raipur)",
    "Devendra Nagar",
    "Shankar Nagar",
    "Byron Bazaar",
    "Kachna",
    "Mahoba Bazar",
    "Samta Colony",
    "Pandri Bus Stand",
    "Mowa",
    "Amanaka",
    "GE Road",
    "Railway Colony",
    "Urla Industrial Area",
    "Science College Area"
  ],
  roorkee: [
    "Roorkee Railway Station",
    "IIT Roorkee Campus",
    "Civil Lines (Roorkee)",
    "Ganeshpur",
    "Purani Tehsil",
    "Solani Aqueduct",
    "Bus Stand Roorkee",
    "Ramnagar (Roorkee)",
    "Roorkee Cantonment",
    "Bajuheri",
    "Haridwar Road",
    "Mundiyaki",
    "Malviya Chowk",
    "Jhanda Chowk",
    "Shivaji Colony",
    "Neemrana (Roorkee)",
    "Bhagirath Kunj",
    "Green Park",
    "Sheikhpuri",
    "IIT Roorkee Gate"
  ],
  salem: [
    "Salem Town Railway Station",
    "Salem Junction",
    "New Bus Stand (Salem)",
    "Old Bus Stand (Town)",
    "Mettur",
    "Yercaud",
    "Attur",
    "Sankagiri",
    "Edappadi",
    "Omalur",
    "Karuppur",
    "Ammapet",
    "Gorimedu",
    "Hasthampatty",
    "Steel Plant",
    "Suramangalam",
    "Seelanaickenpatti",
    "Fairlands",
    "Dadagapatti",
    "Kannankurichi"
  ],
  surat: [
    "Surat Railway Station",
    "Surat International Airport",
    "Ring Road (Textile Market)",
    "Surat Diamond Bourse",
    "Varachha",
    "Adajan",
    "Katargam",
    "Udhna",
    "Hazira",
    "Dumas Beach",
    "City Light",
    "Parle Point",
    "Athwa Lines",
    "Nanpura",
    "Ghod Dod Road",
    "SVNIT Surat (Ichhanath)",
    "Pal",
    "Chowk Bazaar",
    "Bhatar",
    "Sachin GIDC"
  ],
  thane: [
    "Thane Railway Station",
    "Thane West",
    "Thane East",
    "Naupada",
    "Panchpakhadi",
    "Ghodbunder Road",
    "Majiwada",
    "Kolshet",
    "Vasant Vihar",
    "Kopri",
    "Louis Wadi",
    "Wagle Estate",
    "Balkum",
    "Kalwa",
    "Upvan",
    "Hiranandani Estate",
    "Kasarvadavali",
    "Kopri Colony",
    "Ovala",
    "Mumbra"
  ],
  tiruchirappalli: [
    "Tiruchirappalli Junction",
    "Trichy International Airport",
    "Srirangam",
    "Rockfort (Malai Kottai)",
    "Thillai Nagar",
    "Central Bus Stand (Trichy)",
    "Chatram Bus Stand",
    "Tiruchirappalli Cantonment",
    "BHEL Township (Kailasapuram)",
    "Thuvakudi (NIT Trichy)",
    "Golden Rock",
    "Woraiyur",
    "KK Nagar (Trichy)",
    "TVS Tollgate",
    "Manapparai",
    "Samayapuram",
    "Gundur",
    "Tiruvanaikoil",
    "Puthur",
    "Ponmalai"
  ],
  trivandrum: [
    "Thiruvananthapuram Central Station",
    "Trivandrum International Airport",
    "East Fort",
    "Statue Junction",
    "Palayam",
    "Technopark (Kazhakkoottam)",
    "Kazhakoottam",
    "Medical College (Thiruvananthapuram)",
    "Vellayambalam",
    "Kovalam",
    "Thampanoor",
    "Ulloor",
    "Vazhuthacaud",
    "Pattom",
    "Nemom",
    "Thirumala",
    "Perorkada",
    "Attingal",
    "Neyyattinkara",
    "Vizhinjam"
  ],
  varanasi: [
    "Varanasi Junction (Cantt)",
    "Lal Bahadur Shastri Airport",
    "Kashi Vishwanath Temple",
    "Dashashwamedh Ghat",
    "Assi Ghat",
    "Godowlia",
    "Banaras Hindu University (BHU)",
    "Lanka",
    "Sigra",
    "Cantt Area (Varanasi Cantonment)",
    "Sarnath",
    "Chowk (Vishwanath Gali)",
    "Pandeypur",
    "Mahmoorganj",
    "Ramnagar",
    "Mughalsarai (Deen Dayal Upadhyaya Jn)",
    "Maldahiya",
    "Bhelupur",
    "Kabir Chaura",
    "Chetganj"
  ],
  vellore: [
    "VIT University",
    "Katpadi Junction",
    "Vellore New Bus Stand",
    "CMC Hospital",
    "Vellore Fort",
    "Bagayam",
    "Gandhi Nagar",
    "Filter Bed Road",
    "Sripuram Golden Temple",
    "Allapuram",
    "Sathuvachari",
    "OTP Campus",
    "Velapadi",
    "Viruthampet",
    "Palavansathu",
    "Walajapet",
    "Arcot",
    "Pennathur",
    "Thiruvalam",
    "Gudiyatham"
  ],
  vijayawada: [
    "Vijayawada Junction",
    "Vijayawada International Airport (Gannavaram)",
    "Pandit Nehru Bus Station (PNBS)",
    "Benz Circle",
    "MG Road (Bandar Road)",
    "Eluru Road",
    "Governorpet",
    "Autonagar",
    "One Town",
    "Kanaka Durga Temple",
    "Prakasam Barrage",
    "Bhavanipuram",
    "Patamata",
    "Labbipet",
    "Singhnagar",
    "Poranki",
    "Gollapudi",
    "Tadepalli",
    "Gunadala",
    "Kankipadu"
  ],
  visakhapatnam: [
    "Visakhapatnam Railway Station",
    "Visakhapatnam International Airport",
    "Dwaraka Nagar",
    "Gajuwaka",
    "MVP Colony",
    "Siripuram",
    "RK Beach (Beach Road)",
    "Steel Plant Township",
    "Arilova",
    "Seethamadhara",
    "Lawson's Bay",
    "Old Post Office (Town Kotha Road)",
    "Waltair Uplands",
    "NAD Junction",
    "Gopalapatnam",
    "Simhachalam",
    "Bhimili",
    "Anakapalle",
    "Yendada",
    "Murali Nagar"
  ],
  warangal: [
    "Warangal Railway Station",
    "Kazipet Junction",
    "Hanamkonda",
    "NIT Warangal (Kazipet)",
    "Warangal Fort",
    "Thousand Pillar Temple",
    "Subedari",
    "Enumamula Market",
    "Kazipet Dargah",
    "Mahboobabad Road",
    "JPN Road",
    "Mattwada",
    "Narsampet Road",
    "Chintal",
    "Mulkanoor",
    "University Arts & Science College",
    "NGO's Colony",
    "Shyampet",
    "Hunter Road",
    "Parkal"
  ]
};


const API_KEY = process.env.GOOGLE_MAPS_API_KEY;

async function geocodeWithNominatim(place, city) {
  const q   = encodeURIComponent(`${place}, ${city}, India`);
  const url = `https://nominatim.openstreetmap.org/search?format=json&q=${q}&countrycodes=in&limit=1`;
  const res = await axios.get(url, { headers: { 'User-Agent':'Unipool-Geocoder/1.0' } });
  if (!res.data.length) throw new Error(`No Nominatim result for "${place}, ${city}"`);
  const { lat, lon } = res.data[0];
  return { lat: +lat, lon: +lon };
}

async function geocodeWithGoogle(place, city) {
  const q   = encodeURIComponent(`${place}, ${city}, India`);
  const url = `https://maps.googleapis.com/maps/api/geocode/json?address=${q}&key=${API_KEY}`;
  const res = await axios.get(url);
  const body = res.data;
  if (body.status === 'OK' && body.results.length) {
    const { lat, lng } = body.results[0].geometry.location;
    return { lat, lon: lng };
  }
  throw new Error(`Google failed (${body.status})`);
}

async function geocode(place, city) {
  if (API_KEY) {
    try {
      return await geocodeWithGoogle(place, city);
    } catch (e) {
      console.warn(`Google error for "${place}": ${e.message}, falling back`);
    }
  }
  return geocodeWithNominatim(place, city);
}

(async () => {
  const output = {};

  try {
    if (API_KEY) {
      const test = await axios.get(
        `https://maps.googleapis.com/maps/api/geocode/json?address=Delhi&key=${API_KEY}`
      );
      console.log(`✅ Google test: ${test.data.status}`);
    } else {
      const test = await axios.get(
        'https://nominatim.openstreetmap.org/search?format=json&q=Delhi&countrycodes=in&limit=1',
        { headers:{ 'User-Agent':'Unipool-Geocoder/1.0' } }
      );
      console.log(`✅ Nominatim test: ${test.data.length} result(s)`);
    }
  } catch (err) {
    console.error(`❌ Geocoder test failed: ${err.message}`);
    process.exit(1);
  }

  for (const [city, places] of Object.entries(POPULAR_LOCATIONS)) {
    console.log(`\n⏳ Geocoding "${city}" (${places.length})…`);
    output[city] = {};
    let i = 0;
    for (const place of places) {
      try {
        const coords = await geocode(place, city);
        output[city][place] = coords;
        process.stdout.write(`✔ ${place}\n`);
      } catch (e) {
        process.stdout.write(`✖ ${place}: ${e.message}\n`);
      }
      i++;
      await new Promise(r => setTimeout(r, API_KEY ? 200 : 1000));
    }
  }

  const fileContent =
    'export const POPULAR_LOCATIONS_WITH_COORDS = ' +
    JSON.stringify(output, null, 2) +
    ';\n';

  const outPath = path.resolve(process.cwd(), 'popular-with-coords.js');
  fs.writeFileSync(outPath, fileContent, 'utf-8');
  console.log(`\n✅ Wrote ${outPath}`);
})();
