import { StyleSheet, Dimensions } from "react-native";
import AppColors from "../../design_systems/colors";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  customHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: AppColors.primaryLightGreen,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 12,
    marginHorizontal: 8,
    marginTop: 8,
  },
  customHeaderLeft: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  headerBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
  },
  headerDivider: {
    width: 2,
    height: 56,
    backgroundColor: "#b3d233",
    marginHorizontal: 12,
    borderRadius: 1,
    alignSelf: "center",
  },
  customHeaderRight: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    fontSize: 22,
    fontWeight: "700",
    color: AppColors.basicBlack,
    marginBottom: 8,
  },
  container: {
    flex: 1,
    backgroundColor: AppColors.primaryLightGreen,
  },
  safeArea: {
    flex: 1,
    backgroundColor: AppColors.primaryLightGreen,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: AppColors.primaryLightGreen,
  },
  brandInfoHeaderRow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    backgroundColor: AppColors.primaryLightGreen,
  },
  ridesHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
    paddingTop: 35,
    paddingBottom: 8,
    backgroundColor: AppColors.primaryLightGreen,
  },
  ridesHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  ridesHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flex: 0,
    gap: 8,
  },
  backButton: {
    padding: 8,
  },
  ridesCountText: {
    fontSize: 16,
    color: AppColors.basicBlack,
    marginLeft: 8,
    fontFamily: "NunitoSans_400Regular",
  },
  searchMetaText: {
    fontSize: 12,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
    marginTop: 2,
    marginLeft: 8,
  },
  filterButton: {
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  filterButtonText: {
    color: AppColors.basicWhite,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'NunitoSans_500Medium',
  },
  createRideButton: {
    backgroundColor: AppColors.basicBlack,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 0,
  },
  createRideButtonText: {
    color: AppColors.basicWhite,
    fontSize: 16,
    fontFamily: "NunitoSans_400Regular",
  },
  headerTitle: {
    fontSize: 20,
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_400Regular",
    flex: 1,
    textAlign: "center",
    marginRight: 40,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  headerText: {
    fontSize: 16,
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_400Regular",
    marginLeft: 8,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    marginTop: 0,
  },
  navBarView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: AppColors.basicWhite,
    paddingTop: 12,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
    noRidesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  noRidesTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: AppColors.basicBlack,
    fontFamily: 'NunitoSans_600SemiBold',
    marginBottom: 8,
  },
  noRidesSubtitle: {
    fontSize: 16,
    color: AppColors.secondaryDarkGreen,
    fontFamily: 'NunitoSans_400Regular',
    textAlign: 'center',
    marginBottom: 24,
  },
  adjustFiltersButton: {
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  adjustFiltersButtonText: {
    color: AppColors.basicWhite,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'NunitoSans_600SemiBold',
  },
  rideCardWrapper: {
    marginBottom: 16,
    backgroundColor: AppColors.basicWhite,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  rideEnhancements: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#f5f5f5',
  },
  relevanceContainer: {
    marginBottom: 8,
  },
  relevanceScore: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF6B35',
    fontFamily: 'NunitoSans_600SemiBold',
  },
  matchReason: {
    fontSize: 12,
    color: AppColors.secondaryDarkGreen,
    fontFamily: 'NunitoSans_400Regular',
    marginBottom: 8,
  },
  distanceInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  distanceText: {
    fontSize: 12,
    color: AppColors.secondaryDarkGreen,
    fontFamily: 'NunitoSans_400Regular',
  },
  hostInfo: {
    marginTop: 4,
  },
  hostName: {
    fontSize: 12,
    color: AppColors.basicBlack,
    fontFamily: 'NunitoSans_500Medium',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  filterModal: {
    backgroundColor: AppColors.basicWhite,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    paddingTop: 8,
  },
  
  // New improved filter modal styles
  filterModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  filterModalContent: {
    backgroundColor: AppColors.secondaryDarkGreen,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    minHeight: '60%',
  },
  filterCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterCloseButtonText: {
    fontSize: 18,
    color: AppColors.basicWhite,
    fontWeight: '600',
  },
  filterSelector: {
    backgroundColor: AppColors.basicBlack,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: AppColors.primaryLightGreen + '30',
  },
  filterSelectorText: {
    fontSize: 16,
    color: AppColors.basicWhite,
    fontFamily: 'NunitoSans_400Regular',
    flex: 1,
  },
  filterSelectorArrow: {
    fontSize: 14,
    color: AppColors.basicWhite,
    marginLeft: 8,
  },
    selectorModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  selectorModalContent: {
    backgroundColor: AppColors.secondaryDarkGreen,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    minHeight: '40%',
  },
  selectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.primaryLightGreen + '30',
  },
  selectorTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: AppColors.primaryLightGreen,
    fontFamily: 'NunitoSans_600SemiBold',
  },
  selectorCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: AppColors.basicBlack,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectorCloseButtonText: {
    fontSize: 18,
    color: AppColors.basicWhite,
    fontWeight: '600',
  },
  selectorOptions: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  selectorOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.basicWhite + '20',
    borderRadius: 8,
    marginBottom: 4,
  },
  selectedSelectorOption: {
    backgroundColor: AppColors.basicBlack,
    borderColor: AppColors.primaryLightGreen,
    borderWidth: 1,
  },
  selectorOptionText: {
    fontSize: 16,
    color: AppColors.basicWhite,
    fontFamily: 'NunitoSans_400Regular',
  },
  selectedSelectorOptionText: {
    color: AppColors.primaryLightGreen,
    fontWeight: '600',
    fontFamily: 'NunitoSans_600SemiBold',
  },
  checkmark: {
    fontSize: 18,
    color: AppColors.primaryLightGreen,
    fontWeight: 'bold',
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  filterTitle: {
    fontSize: 20,
    color: AppColors.basicWhite,
    fontFamily: 'NunitoSans_400Regular',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: AppColors.secondaryDarkGreen,
    fontWeight: '600',
  },
  filterContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  filterGroup: {
    marginBottom: 24,
  },
  filterLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: AppColors.primaryLightGreen,
    fontFamily: 'NunitoSans_600SemiBold',
    marginBottom: 8,
  },
  filterInput: {
    borderWidth: 1,
    borderColor: AppColors.primaryLightGreen + '30',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'NunitoSans_400Regular',
    backgroundColor: AppColors.basicBlack,
    color: AppColors.basicWhite,
  },
  picker: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    backgroundColor: '#fafafa',
  },
  filterButtons: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 34,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    gap: 12,
  },
  clearButton: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  clearButtonText: {
    color: AppColors.secondaryDarkGreen,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'NunitoSans_600SemiBold',
  },
  applyButton: {
    flex: 2,
    backgroundColor: AppColors.secondaryDarkGreen,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  applyButtonText: {
    color: AppColors.basicWhite,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'NunitoSans_600SemiBold',
  },
  
  // Original styles from the old stylesheet
  rideCard: {
    backgroundColor: AppColors.basicWhite,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  locationDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  fromDot: {
    backgroundColor: AppColors.secondaryDarkGreen,
  },
  toDot: {
    backgroundColor: AppColors.primaryLightGreen,
  },
  locationText: {
    fontSize: 16,
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_400Regular",
    flex: 1,
  },
  dottedLine: {
    width: 2,
    height: 30,
    backgroundColor: "transparent",
    borderStyle: "dotted",
    borderWidth: 1,
    borderColor: AppColors.secondaryDarkGreen,
    marginLeft: 5,
    marginVertical: 8,
  },
  rideDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  timeIcon: {
    marginRight: 8,
  },
  timeText: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  priceContainer: {
    backgroundColor: AppColors.primaryLightGreen,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  priceText: {
    fontSize: 16,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  driverInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  driverLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  driverImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: AppColors.primaryLightGreen,
    marginRight: 12,
  },
  driverDetails: {
    flex: 1,
  },
  driverName: {
    fontSize: 16,
    fontWeight: "500",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  vehicleInfo: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  seatsContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  seatIcon: {
    marginRight: 4,
  },
  seatsText: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyIcon: {
    marginBottom: 24,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
    marginBottom: 12,
    textAlign: "center",
  },
  emptyDescription: {
    fontSize: 16,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
    textAlign: "center",
    lineHeight: 24,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  // Detail Screen Styles
  gradientHeader: {
    height: height * 0.3,
    justifyContent: "flex-end",
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  detailBackButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 20,
    padding: 8,
  },
  routeInfo: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginTop: -40,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  routeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  routeTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  dateTimeBadge: {
    backgroundColor: AppColors.primaryLightGreen,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  dateTimeText: {
    fontSize: 12,
    fontWeight: "500",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  routePath: {
    marginBottom: 20,
  },
  routeStop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  stopDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  stopText: {
    fontSize: 16,
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_400Regular",
  },
  vehicleSection: {
    backgroundColor: AppColors.basicWhite,
    margin: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  vehicleHeader: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
    marginBottom: 16,
  },
  vehicleIllustration: {
    alignItems: "center",
    marginBottom: 20,
  },
  vehicleImage: {
    width: 120,
    height: 80,
    marginBottom: 8,
  },
  vehicleModel: {
    fontSize: 16,
    fontWeight: "500",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  vehiclePlate: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  driverSection: {
    backgroundColor: AppColors.basicWhite,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  driverHeader: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
    marginBottom: 16,
  },
  driverProfile: {
    flexDirection: "row",
    alignItems: "center",
  },
  driverAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: AppColors.primaryLightGreen,
    marginRight: 16,
  },
  driverInfo2: {
    flex: 1,
  },
  driverName2: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
    marginBottom: 4,
  },
  driverRating: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
    marginBottom: 4,
  },
  driverExperience: {
    fontSize: 14,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  mapSection: {
    backgroundColor: AppColors.basicWhite,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mapHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  mapTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_600SemiBold",
  },
  mapPlaceholder: {
    height: 200,
    backgroundColor: "#f8f9fa",
    justifyContent: "center",
    alignItems: "center",
  },
  mapText: {
    fontSize: 16,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  bottomSection: {
    backgroundColor: AppColors.basicWhite,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  totalPriceLabel: {
    fontSize: 16,
    color: AppColors.secondaryDarkGreen,
    fontFamily: "NunitoSans_400Regular",
  },
  totalPriceValue: {
    fontSize: 24,
    fontWeight: "700",
    color: AppColors.basicBlack,
    fontFamily: "NunitoSans_700Bold",
  },
  requestButton: {
    backgroundColor: AppColors.secondaryDarkGreen,
    borderRadius: 25,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  requestButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: AppColors.basicWhite,
    fontFamily: "NunitoSans_600SemiBold",
  },
});

export default styles;